<div class="page-content clearfix sidebar-page">
    <div class="page-content-wrapper">
        <div class="page-content-inner">
            <div id="page-header" class="clearfix">
                <div class="page-header">
                    
                    <h2><?=saudacao();?> <?= retorna_dados_cookie_usuario_adm('usuario');?></h2>
                    <h3><?= dias_semana();?></h3>
                    <span class="txt">
                       
                    </span>
                    
                </div>
            </div>
           
           
    </div>
</div>    